### ISSUE TITLE
"Yes" "No" not heard on mycroft core

### ISSUE THREAD

**Issue by MongolXel** [reginaneon/AVmusic#1]
When the skill ask to confirm before playing the track mycroft apparently gets deaf; it's necessary to confirm through the cli (neither "yes", "no" , "proceed" seem to function) .

**Comment by reginaneon** [comment]
Thank you for pointing it out, I fixed the issue in the latest commit. Please pull if it doesn't take effect
I really appreciate the feedback.

**Comment by reginaneon** [comment]
Let me know if the problem persists or anything else happens :)
